# Generated by Django 3.0.3 on 2022-08-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='imgimg',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
    ]
